### ISSUE TITLE
Check and warn if redirect url is being used upon Alias creation

### ISSUE THREAD

**Issue by raulpires** [ilya40umov/KotLink#13]
When creating/updating an Alias, check if the redirect url is already being used. It can be the case that the person making the addition/update might not be aware that this is already be in other context/namespace. 

By saying something like "this is already being used in this <scope>" the person can become aware of a context/namespace she is not aware and that it is related to what she wants. Or maybe it makes complete sense to add duplicate and that's also fine :smiley:

**Comment by ilya40umov** [comment]
Closing this one for now. Although, I might return to this one in the future.
