### ISSUE TITLE
alias string interpolation

### ISSUE THREAD

**Issue by arahayrabedian** [ilya40umov/KotLink#23]
Some links have obvious interpolable patterns that it's not nice to have to enter multiple aliases for, it's a little difficult with order-insensitivity, but would be nice to have something like:

`kk_alias_interpolate-me` --> `https://some.domain.here/{interpolate_me}`

so you could do `kk alias asdfasdf` and get `https://some.domain.here/asdfasdf` as the redirect link

don't know how you'd deal with `kk asdfasdf alias` though

**Comment by ilya40umov** [comment]
Closing this one for now, but I might return to this as it's a valid feature request.
