### ISSUE TITLE
KOTLINK_SECURITY_OAUTH_ALLOWED_EMAILS doesn't work

### ISSUE THREAD

**Issue by rotarur** [ilya40umov/KotLink#32]
Hi,

The documentations says `The second requirement is G Suite or if one's team is really small they can let everybody use their personal gmail accounts to authenticate.` but it doesn't work. It's always trying to use google oauth system.

My team is small and we don't have GSuite, what we can do in this case?

Bests

**Comment by ilya40umov** [comment]
@rotarur thanks for the report! Which image tag / version are you using?

**Comment by ilya40umov** [comment]
@rotarur I've been testing against the latest version of Kotlink and it's functioning as expected:
```
KOTLINK_SECURITY_OAUTH_ALLOWED_EMAIL_REGEX='^$' KOTLINK_SECURITY_OAUTH_ALLOWED_EMAILS='user1@gmail.com,user2@gmail.com' ./gradlew bootRun
```

**Comment by rotarur** [comment]
thanks for the reply

I'm always getting the same response even in inkognito mode

```Authorization Error
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.```

**Comment by ilya40umov** [comment]
@rotarur 
This can only mean that your OAuth2 configuration is not correct.
Did you follow the steps "Obtain OAuth2 Client ID" and "Set Up OAuth2" from [the deployment guide](https://kotlink.org/docs/deployment-guide.html)?
If yes, I recommend that you double-check that you have `https://${YOUR_KOTLINK_SERVER_ADDRESS}/login` under "Authorized redirect URLs." in Google API Console, where `${YOUR_KOTLINK_SERVER_ADDRESS}` is the domain name where you are running KotLink.

**Comment by ilya40umov** [comment]
P.S. By default, if you don't configure OAuth2, KotLink is going to use the default OAuth client that only works when you are running under localhost:8080.

**Comment by rotarur** [comment]
> P.S. By default, if you don't configure OAuth2, KotLink is going to use the default OAuth client that only works when you are running under localhost:8080.

right, this is what i wanted to avoid. we're using office outlook as email provider and to configure oauth i would need to use my private email. i wanted to avoid personal configurations. from docs i understood that for small companies i could use allowed emails only

**Comment by ilya40umov** [comment]
Ah, I see. The issue is that so far KotLink has only been used with Google as the OAuth provider. For which you need to:
a) set up the oauth client on Google side
b) configure the oauth client in KotLink with client info / secret from Google console
c) set up the list of emails which can access the server (but all of these must come from the Google OAuth)

I'm quite certain that Spring Boot should allow to use other auth providers like Okta or Outlook, but that will probably require some changes in the code etc.

**Comment by rotarur** [comment]
sad :(
