### ISSUE TITLE
dynamic setup instructions

### ISSUE THREAD

**Issue by arahayrabedian** [ilya40umov/KotLink#9]
It may make setup more seamless to detect somebody's browser (or just allow them to choose) from within the kotlink webapp, along with ready-to-paste values to insert in the appropriate places.

this would make setting up something like the search engine suggestion-engine less error prone and more convenient.

**Comment by ilya40umov** [comment]
Implemented by https://github.com/ilya40umov/KotLink/commit/795be26162d12463a61cf458cc5e5e3961d8022c
